Alias /memcached "D:/saharalaragon/laragon-6.0-minimal/etc/apps/memcached/"

# to give access from outside 
# replace the lines
#
# Require local 
#
# by
#
# Require all granted
#

<Directory "D:/saharalaragon/laragon-6.0-minimal/etc/apps/memcached/">
	Options Indexes FollowSymLinks MultiViews
	AllowOverride all
	
	Require local

</Directory>
